language: php

before_install:
    - phpenv config-rm xdebug.ini || return 0
    - pecl install pcov
    - pear config-set preferred_state alpha
    - pecl install runkit7

install:
    - travis_retry composer install --no-progress --prefer-dist --ignore-platform-reqs
    - tests/testApp/bin/console cache:warmup --env=test

script:
    - ./vendor/bin/phpcs --standard=./ruleset.xml --colors -p src/ tests/
    - ./vendor/bin/phpstan analyse -c ./phpstan.neon -l 8 src/ tests/
    - ./vendor/bin/paratest -c ./vendor/hanaboso/php-check-utils/phpunit.xml.dist -p 4 tests/Unit
    - ./vendor/bin/paratest -c ./vendor/hanaboso/php-check-utils/phpunit.xml.dist -p 4 --coverage-clover var/coverage.xml --whitelist src tests
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - php coveralls.phar --verbose --config .coveralls.yml

php:
    - 7.4

branches:
    only:
        - master

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false