version: '3.5'
services:
    app:
        image: hanabosocom/php-dev:php-7.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:${SSH_AUTH}
            - ${HOME}/dev/.composer:${HOME}/dev/.composer
        environment:
            - APP_ENV=dev
            - KERNEL_CLASS=UtilsTests\Kernel
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - COMPOSER_HOME=${HOME}/dev/.composer